version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"  # ✅ Allow Public Key Retrieval
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:  # ✅ Healthcheck to ensure MySQL is ready
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: appletreecy/backend:1.0
    restart: always
    env_file: .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  frontend:
    image: appletreecy/frontend:1.0
    restart: always
    depends_on:
      - backend
    ports:
      - "4173:4173"
    environment:
      - VITE_API_BASE_URL=http://192.168.1.59:8000/api

volumes:
  mysql-data:
